"""Jester AI Company package.

Provides company introspection, agent inventory, and operational state inspection.
"""

from .core import (
    Approval,
    ApprovalStatus,
    Artifact,
    ArtifactType,
    Company,
    Employee,
    Project,
    RunStatus,
    Task,
    TaskResult,
    TaskRun,
    TaskStatus,
    VerificationResult,
    create_default_company,
)
from .execution import TaskExecutor
from .registry import RECOGNIZED_AGENTS, get_agent_inventory
from .service import (
    CompanyService,
    CompanyServiceError,
    ExecutionError,
    InvalidTaskStateError,
    ProjectNotFoundError,
    RunNotFoundError,
    TaskNotFoundError,
)

from .status import (
    DEFAULT_COMPANY_NAME,
    DEFAULT_PURPOSE,
    DEFAULT_LIFECYCLE_STAGE,
    DEFAULT_HEALTH_STATUS,
    IMPLEMENTED_CAPABILITIES,
    format_status_console,
    get_company_status,
    get_pipeline_telemetry,
)

from .control_center import ControlCenterHandler, create_server, run_control_center
from .runtime import (
    AgentExecutionResult,
    AntigravityRuntime,
    AntigravityRuntimeError,
    InvalidAgentError,
)
from .proposal import (
    CEOActionProposal,
    ProposalError,
    ProposalParseError,
    ProposalValidationError,
    build_task_proposal_prompt,
    extract_json_text,
    parse_and_validate_proposal,
)
from .product_result import (
    ProductDeliverable,
    ProductResultError,
    ProductResultParseError,
    ProductResultValidationError,
    ProductTaskResult,
    build_product_execution_prompt,
    extract_product_json_text,
    parse_and_validate_product_result,
)
from .research_result import (
    ResearchFinding,
    ResearchResultError,
    ResearchResultParseError,
    ResearchResultValidationError,
    ResearchSource,
    ResearchTaskResult,
    build_research_execution_prompt,
    extract_research_json_text,
    parse_and_validate_research_result,
)
from .materializer import (
    MaterializationError,
    atomic_write_text,
    compute_sha256,
    format_product_report,
    format_research_report,
    get_safe_run_artifacts_dir,
    materialize_specialist_artifact,
)

__version__ = "0.1.0"

__all__ = [
    "Approval",
    "ApprovalStatus",
    "Artifact",
    "ArtifactType",
    "Company",
    "Employee",
    "Project",
    "RunStatus",
    "Task",
    "TaskResult",
    "TaskRun",
    "TaskStatus",
    "VerificationResult",
    "create_default_company",
    "TaskExecutor",
    "CompanyService",
    "CompanyServiceError",
    "ProjectNotFoundError",
    "TaskNotFoundError",
    "RunNotFoundError",
    "InvalidTaskStateError",
    "ExecutionError",
    "ControlCenterHandler",
    "create_server",
    "run_control_center",
    "RECOGNIZED_AGENTS",
    "get_agent_inventory",
    "DEFAULT_COMPANY_NAME",
    "DEFAULT_PURPOSE",
    "DEFAULT_LIFECYCLE_STAGE",
    "DEFAULT_HEALTH_STATUS",
    "IMPLEMENTED_CAPABILITIES",
    "format_status_console",
    "get_company_status",
    "get_pipeline_telemetry",
    "AgentExecutionResult",
    "AntigravityRuntime",
    "AntigravityRuntimeError",
    "InvalidAgentError",
    "CEOActionProposal",
    "ProposalError",
    "ProposalParseError",
    "ProposalValidationError",
    "build_task_proposal_prompt",
    "extract_json_text",
    "parse_and_validate_proposal",
    "ProductDeliverable",
    "ProductResultError",
    "ProductResultParseError",
    "ProductResultValidationError",
    "ProductTaskResult",
    "build_product_execution_prompt",
    "extract_product_json_text",
    "parse_and_validate_product_result",
    "ResearchFinding",
    "ResearchResultError",
    "ResearchResultParseError",
    "ResearchResultValidationError",
    "ResearchSource",
    "ResearchTaskResult",
    "build_research_execution_prompt",
    "extract_research_json_text",
    "parse_and_validate_research_result",
    "MaterializationError",
    "atomic_write_text",
    "compute_sha256",
    "format_product_report",
    "format_research_report",
    "get_safe_run_artifacts_dir",
    "materialize_specialist_artifact",
    "__version__",
]

